### ISSUE TITLE
Startup issue - HTTP service not responding?

### ISSUE THREAD

**Issue by erikcvisser** [jojo141185/mopidy-docker#1]
Hi there, thanks for you initiative in making the various pieces of work available in a single docker container!
I immediately tried it out, but seem to hit an error. Wanted to check if you recognize it before spending a lot of time debugging.

Running on: Raspberry Pi (3B), as root
Version: jojo141185/mopidy:edge

Warnings/errors from the log 
![image](https://user-images.githubusercontent.com/3143244/206749997-287db34f-74b1-4b4d-990d-273723168dc7.png)
![image](https://user-images.githubusercontent.com/3143244/206750081-d1cd6792-2c3b-49a8-906c-67cb6d925089.png)

It reports that it started on :6680 (as per config and opened ports in Docker run command). However, when accessing it via the browser, it just keeps loading. Firewall/ufw etc is turned off, so that's not the issue. It also doesn't time out, it just won't respond. 
![image](https://user-images.githubusercontent.com/3143244/206750797-d4b8fcca-6cb9-4d40-bdb8-154380184b6d.png)

Running the regular Mopidy service directly on the Pi (but without Spotify) does work. That service obviously is not active now.

Reporting it here because you also asked for people to test and provide feedback. Let me know if I can provide any more information.

Thanks!

**Comment by jojo141185** [comment]
Please verify that you are binding to the correct device in the Docker container.
Try the follwoing settings in mopidy.conf to listen on any ip and allow access to the web interface from everywhere:
```
[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = iris

[mpd]
hostname = 0.0.0.0
```

**Comment by erikcvisser** [comment]
Thanks for the response. I’ve tried with these more explicit settings as well, but same error. I did pull the latest :edge version as well. 

It works fine over MPD, so the device and config seem fine. The exception in HttpServer thread seems to be the issue. A permission error, which is interesting. I’ll see if I can build my own image and explore a bit further.

**Comment by erikcvisser** [comment]
Resolved - it had to due with my host. The Raspberry Pi 3b is running Raspbian Buster. 
libseccomp2 was on version 2.3.3. Installing a backport from bullseye (v2.5.1) worked.

Thanks again for packaging it like this!

https://github.com/freqtrade/freqtrade/issues/6183#issuecomment-1016940306
