### ISSUE TITLE
Docker container size on disk grows tremendously

### ISSUE THREAD

**Issue by RensOliemans** [jojo141185/mopidy-docker#11]
Thank you for creating this Docker image, it's been working fantastically for the past weeks.
However, it has grown to 12.6GB throughout the past 4 weeks, and its directory in `/var/lib/docker/overlay2` has grown to 25GB.

Are there things that I have misconfigured, or is there something that can be changed in this repo? I am using a `docker-compose.yml` virtually identical to the one in your repo. I am now periodically doing `docker-compose down && docker-compose up -d`, but that is quite arbitrary and error-prone: if I forget to do so once in a while, my Pi stops working properly :grin:. Doing it via `cron` isn't ideal either, since I might be listening music at 4:00 AM on Sunday night!

**Comment by jojo141185** [comment]
The file system of the container might differ from the contents of the image after it is created if changes are made to the writeable layer of the container.

You can use docker diff to check what changes have been made to files and directories inside the mopidy container. The command accepts the ID or name of the container - hereafter referred to as "mopidy".
`docker diff mopidy
`

After that, you can run a shell on the running container and see where most of the data was written. 
For example:
```
sudo docker exec -it mopidy /bin/bash
du -h /var/lib/mopidy/
```

It could be that you have a large local database or use other plugins that write large amounts of data. 

I can't reproduce this behavior on my end at the moment.

**Comment by RensOliemans** [comment]
Thanks for these commands. `docker diff mopidy` shows a lot of entries in `/var/lib/mopidy/.cache`. That `.cache` folder takes up ~800MB, since 2 days ago (date of container creation). I will check this if the container increases, to see if it is said cache folder which increases by a lot.

I will report back in a couple of days whether this is indeed the case. Would you know whether this is something for [mopidy/mopidy-spotify](https://github.com/mopidy/mopidy-spotify/) to look into, or if this is a configuration error on my part?

**Comment by RensOliemans** [comment]
About one and a half week later, the container takes up 1.3GB more than before, `docker exec mopidy du -sh /var/lib/mopidy/.cache` gives me 1.3G.

This seems to grow indefinitely, are you aware of any mopidy settings that could mitigate/limit this behaviour that are passable via Docker? I can imagine that this is out of scope of your repository though.

**Comment by RensOliemans** [comment]
Awesome, thanks for that pointer! I agree in that the "issue" is indeed in that "feature" you think. Would you know where I can find the documentation for mopidy-spotify? After your pointer I found https://github.com/mopidy/mopidy-spotify/blob/master/mopidy_spotify/ext.conf, which suffices for this, but not some page with documentation or explanation. I'm closing this as I agree that it isn't likely an issue related to this docker image, thanks for the help in any case.
