### ISSUE TITLE
Question: How to add a new python extension using docker-compose.yml

### ISSUE THREAD

**Issue by viktak** [jojo141185/mopidy-docker#13]
As the title says: Can you please elaborate on how to add a new python extension using `docker-compose.yml`? I tried this:
```
    environment:
      - 'Mopiqtt'
```
but still I got:
```
mopidy  | WARNING  2023-06-15 09:16:57,502 [7:MainThread] mopidy.config
mopidy  |   Ignoring config section 'mopiqtt' because no matching extension was found
```

Thank you in advance!

**Comment by jojo141185** [comment]
You can use the 'PIP_PACKAGES' environment variable to install specific pip packages when the container is started.

This is an example in docker-compose.yml:
```
environment: 
            # Install additional pip packages
            - PIP_PACKAGES=Mopidy-Party Mopidy-TuneIn
```

**Comment by viktak** [comment]
Ah, I see. Thank you for the clarification. Also, thanks for the custom images, I have learnt a lot from them!
