### ISSUE TITLE
$PIP_PACKAGES install broken

### ISSUE THREAD

**Issue by hackbardc** [jojo141185/mopidy-docker#28]
Hey jojo!

Thanks for producing this container, I run it on a rock64 and rbp 3b. I use the $PIP_PACKAGES var with a docker-compose.yml for yt-dlp and bandcamp. Since a few weeks the install is broken and I have to manually run the command

```
docker exec -it mopidy bash
python3 -m pip install yt-dlp --break-system-packages"
```

I think it's a change in the underlying os which results in abort if the packages are installed without --break-system-packages.  Guess add this on line11 in the entrypoint.sh script will fix these problems.

I'm not super familiar with git so sry for not contributing like I should.
Kind regards, 
hb

**Comment by jojo141185** [comment]
Hi hackbardc,

You are absolutely right. With the release of Bookworm, Debian implemented PEP 668, which prevents pip from installing packages outside of a virtual environment. 

I have disabled this behavior through a global setting in the pip configuration, which hopefully eliminates the need to always append '--break-system-packages'.

Once the Docker images are built, you can test it with the image tag **develop**.

Any further feedback is warmly welcome :-)

**Comment by hackbardc** [comment]
saw your change, nice solution adding the pip config. I Just pulled the latest dev_release image but appears the error is still the same
with
`docker history jojo141185/mopidy:dev_release --no-trunc`
I saw the pip config command is running before installing pip, guess we should place the config cmd after the install..

**Comment by jojo141185** [comment]
The problem seems to be that using the "pip3 config set" command only sets the settings in the user-specific environment. Therefore, the settings were only set for the user "root" and not for the default user "mopidy".
For simplicity, we'll just place the config file under /etc/pip.conf so that 'break-system-packages' is set globally for all system users.

**Comment by jojo141185** [comment]
Tested the changes on latest builds.
Problem should be fixed now!

**Comment by hackbardc** [comment]
Hey
something is still prohibiting the install, now I get
`-- INSTALLING PIP PACKAGES 'yt-dlp Mopidy-Bandcamp' --
ERROR: Invalid requirement: "'yt-dlp"`

`services:
    mopidy:
        container_name: mopidy
        restart: always

        ## Run container as user 
        # select specific privileged user
        user: root
        #user: ${PUID}:${PGID}

        ## Add to audio group 
        # change group name or id to your system's audio group
        group_add:
            - audio

        ## Add audio device 
        # change to your system's audio device
        devices:
            - /dev/snd        
      
        volumes:
            #mopidy config 
            - './config:/config'
            #music files
            - '/storage/dietpi_nfs/music:/var/lib/mopidy/media:ro'
            #local files and playlist
            - './local:/var/lib/mopidy/local'
            - './local/m3u:/var/lib/mopidy/m3u'

            ## Host audio settings
            # Pulseaudio
            #           - '/run/user/1000/pulse/native:/tmp/pulseaudio.socket'
            # Alsa sound
            #- /etc/asound.conf:/etc/asound.conf
            # - /usr/share/alsa:/usr/share/alsa
        ports:
            - '6600:6600'
            - '6680:6680'
        image: 'jojo141185/mopidy:release'
        environment:
            # Host with pulseaudio
            # - PULSE_SERVER=unix:/tmp/pulseaudio.socket
            #- PULSE_COOKIE=/tmp/pulseaudio.cookie
          # PIP_PACKAGES: 'yt-dlp Mopidy-mpris Mopidy-Bandcamp'
            - PIP_PACKAGES='yt-dlp Mopidy-Bandcamp'`

**Comment by jojo141185** [comment]
You shouldn't use the quotation marks...

```
image: 'jojo141185/mopidy:release'
environment:
- PIP_PACKAGES=yt-dlp Mopidy-Bandcamp
```

**Comment by hackbardc** [comment]
yep, thanks for the fix.
