### ISSUE TITLE
entrypoint.sh: Permission denied error

### ISSUE THREAD

**Issue by polcape** [jojo141185/mopidy-docker#3]
Hi, 

when I try to run the container in my compose file I get this error

mopidy      | [dumb-init] /entrypoint.sh: Permission denied

**Comment by jojo141185** [comment]
Hello polcape, 
I think your error might be related to a permission issue of the user mopidy and the iris directory in the Docker container. I have made a small correction in the Dockerfile.
Can you please try again with the latest image on Docker Hub?  It's now available...
`docker pull jojo141185/mopidy:edge`

**Comment by polcape** [comment]
Hello, 
I tried but I get same error

**Comment by vitiko98** [comment]
Setting `--user root` (`user: root` in compose) fixed it for me.

**Comment by polcape** [comment]
Yes @vitiko98 it works! Thanks

Is mopidy-spotify working with this docker image?

**Comment by vitiko98** [comment]
> Is mopidy-spotify working with this docker image?

Working perfectly

**Comment by jojo141185** [comment]
Apart from jumping back and forth in the music track, everything should work so far. The seeking function is not yet implemented in the gstreamer plugin.
Can this issue be closed?

**Comment by polcape** [comment]
Yes @jojo141185, we can close

Thanks!
