### ISSUE TITLE
radionet does not work in docker

### ISSUE THREAD

**Issue by Nahasapeemapetilon** [jojo141185/mopidy-docker#4]
I have fixed it with the instructions from this post 

[https://github.com/plintx/mopidy-radionet/pull/18#issuecomment-1155756129](url)

maybe you can integrate it into the docker ?

**Comment by jojo141185** [comment]
I have integrated the API fix from Emrvb into the mopidy-radionet extension. Thanks for the tip!
You can test it with the docker image tagged "latest":
`docker pull jojo141185/mopidy:latest`

**Comment by Nahasapeemapetilon** [comment]
what is the difference between edge and last?

**Comment by jojo141185** [comment]
The docker tag "edge" is build from master, "latest" from develop branch.

**Comment by jojo141185** [comment]
Added fix to master branch. I think this can be closed.
